export const ANALYTICS_EVENT_NAMES = [
  "page_view",
  "intent_selected",
  "reveal_viewed",
  "result_viewed",
  "day_selected",
  "distant_day_selected",
  "calendar_expanded",
  "calendar_options_opened",
  "calendar_ics_prepared",
  "calendar_google_opened",
  "calendar_google_blocked",
  "calendar_added",
  "intention_saved",
  "intention_viewed",
  "intention_replaced",
  "intention_reminder_opened",
  "intention_reschedule_opened",
  "intention_rescheduled",
  "intention_completed",
  "intention_repeated",
  "intention_cancelled",
  "second_intention_attempted",
  "result_shared",
  "score_explanation_opened",
  "personalization_started",
  "personalization_completed",
  "feedback_helpful",
  "feedback_not_helpful",
  "feedback_form_opened",
  "feedback_form_submitted",
] as const;

export type AnalyticsEventName = typeof ANALYTICS_EVENT_NAMES[number];
